### PR TITLE
Support all pattern type annotations and check kinds

### PR DESCRIPTION
**Pull request by j-hui**
Follow up to #103, addressing remaining concerns:

- [x] actually unroll pattern annotations rather than discarding them
- [x] typecheck type definitions, i.e., check the kind of each type constructor
- [x] document everything lmao

### CODE REVIEW

**Comment by j-hui** [comment]
rip documentation, may lord have mercy on the soul of whoever has to pick up this code (hopefully not me months later, however likely)

**Comment by j-hui** [comment]
Note that there are still some bugs that I've flagged down in #109 

Also there is just no documentation here. Maybe I'll try to write some tomorrow.

**Review by LeoQiao18 — APPROVED** [review]

**Comment by j-hui** [comment]
damn I actually documented everything

**Comment by j-hui** [comment]
LFG

**Pull request merged**
