### PR TITLE
Constraint IR Pretty Printer

### PR DESCRIPTION
**Pull request by jar2333**
Draft PR

### CODE REVIEW

**Comment by jar2333** [comment]
tests are failing right now because the constraint AST is being dumped always, will make it depend on option flag when it's all done

**Comment by jar2333** [comment]
have most of the skeleton needed for pretty printing the IR, I just have to look into the prettyprinter package now

**Comment by leoqiao18** [comment]
@jar2333 Could you update the `Typechecking.hs` module to generate the pretty-print `Doc` only when the flag is provided?

**Review by j-hui — APPROVED** [review]
Fix up the regression test suite with those silly -fail test cases, and then :ship: it!

**Comment by j-hui** [comment]
@jar2333 I updated the failing test error message. Feel free to squashé & mergé whenever!

**Pull request merged**
